version = 0.1

[default.deploy.parameters]
stack_name = "rdc-scraper"
resolve_s3 = true
s3_prefix = "rdc-scraper"
region = "sa-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = [
    "MongoDbUri=<mongodb+srv://...>",
    "MongoDbDatabase=<dev|prod>",
    # "DrinksApiUrl=",
    # "DrinksApiKey=",
    # "ProxyEndpoint=",
    # "ProxyApiKey=",
    "S3ImagesBucket=<bucket-name>",
    # "ResendApiKey=",
    # "EmailSender=",
    # "EmailRecipient=",
]
image_repositories = []

[default.global.parameters]
region = "sa-east-1"
