version = 0.1

[default.deploy.parameters]
stack_name = "rdc-scraper"
resolve_s3 = true
s3_prefix = "rdc-scraper"
region = "sa-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = [
    "DrinksApiUrl=",
    "DrinksApiKey=",
    "ProxyEndpoint=",
    "ProxyApiKey=",
    "S3ImagesBucket=rdc-product-images",
    "ResendApiKey=",
    "EmailSender=",
    "EmailRecipient=",
]
image_repositories = []

[default.global.parameters]
region = "sa-east-1"
